data:
  dataset: "human36m"
  dataset_path_3d: "./data/data_3d_h36m.npz"
  dataset_path_2d: "./data/data_2d_h36m_gt_gmm_norm.npy"
  num_joints: 17
  num_workers: 32
  kpt_left: [4, 5, 6, 11, 12, 13]
  kpt_right: [1, 2, 3, 14, 15, 16]
  pose_model: "./ckpts/gcn_xyz_gt.pth"
  flip_aug: 1

model:
  n_pts: 17
  hid_dim: 96
  emd_dim: 96
  num_layers: 5
  n_head: 4
  dropout: 0.25
  ema_rate: 0.999
  ema: True

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.001
  num_diffusion_timesteps: 51
  skip_type: uniform
  eta: 0.0

training:
  batch_size: 1024
  n_epochs: 800
  n_iters: 5000000
  snapshot_freq: 5000
  validation_freq: 2000
  num_workers: 32

testing:
  test_times: 1
  test_timesteps: 2
  test_num_diffusion_timesteps: 12

optim:
  decay: 60
  optimizer: "Adam"
  lr: 0.001
  lr_gamma: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0

